name:                acc-tch-issue
version:             0.1.0.0
github:              "githubuser/accelerate-llvm-ptx-segfault"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

dependencies:
- base >= 4.7 && < 5
- accelerate
- accelerate-llvm-ptx
- cuda
- hasktorch

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  acc-tch-issue:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - acc-tch-issue
