resolver: lts-22.21

packages:
- .

extra-deps:
- github: llvm-hs/llvm-hs
  # llvm-15
  commit: 5bca2c1a2a3aa98ecfb19181e7a5ebbf3e212b76
  subdirs:
    - llvm-hs
    - llvm-hs-pure
- git: https://github.com/AccelerateHS/accelerate
  # Closest commit to accelerate-llvm in time
  commit: f9eb010ed267357ae0e23d7ddf98186ef2ff5034
- git: https://github.com/AccelerateHS/accelerate-llvm
  # llvm-15 compatible
  commit: 2b5d69448557e89002c0179ea1aaf59bb757a6e3
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-ptx
    - accelerate-llvm-native
- git: https://github.com/hasktorch/hasktorch
  commit: a5a4252a2a60d8caa0fd1c8d1c646165947e3746
  subdirs:
    - hasktorch
    - libtorch-ffi
    - libtorch-ffi-helper
- inline-c-cpp-0.5.0.2
- inline-c-0.9.1.10
